# Only building master means that we don't run two builds for each pull request.
branches:
  only:
  - master

language: dart

env:
- NODE_VERSION=node
- NODE_VERSION=lts/fermium
- NODE_VERSION=lts/erbium

os:
- linux
- osx
- windows

cache: npm

install:
- nvm install $NODE_VERSIOn
- nvm use $NODE_VERSIOn
- npm install
- npm run init

script:
- npm test
