# Only building master means that we don't run two builds for each pull request.
branches:
  only:
  - master

language: node_js

env:
- EMBEDDED_HOST_REF=master

node_js:
- node
- lts/fermium
- lts/erbium

os:
- linux
- osx
- windows

cache: npm

install:
- npm install
- npm run init -- --embedded-host-version="$EMBEDDED_HOST_REF"

script:
- npm test
